name: Build and publish distribution to pypi

on: push

jobs:
  build_wheels:
    name: ${{ matrix.os }} • ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        os: [ubuntu-latest]
        python: [cp37, cp38, cp39, cp310, cp311, cp312, pp37, pp38, pp39, pp310]
        exclude:
          # Exclude Python 3.7 on newer platforms
          - os: macos-14
            python: cp37
          - os: windows-latest
            python: cp37
          - os: macos-14
            python: pp37
          - os: windows-latest
            python: pp37
          # Skip PyPy on Windows
          - os: windows-latest
            python: pp38
          - os: windows-latest
            python: pp39
          - os: windows-latest
            python: pp310
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker cache
        if: runner.os == 'Linux'
        uses: ScribeMD/docker-cache@0.4.0
        with:
          key: docker-${{ runner.os }}-${{ matrix.python }}-${{ github.sha }}
          restore-keys: |
            docker-${{ runner.os }}-${{ matrix.python }}-
            docker-${{ runner.os }}-
            
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22
        env:
          CIBW_BUILD: ${{ matrix.python }}-*
          CIBW_ARCHS_MACOS: auto
          CIBW_TEST_COMMAND: "pytest -v {package}/test"
          CIBW_TEST_REQUIRES: "pytest numpy"
        with:
          package-dir: .
          output-dir: wheelhouse
          config-file: "{package}/pyproject.toml"

      - name: Verify clean directory
        run: git diff --exit-code
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.python }}
          path: ./wheelhouse/*.whl

